### PR TITLE
Add support for PHP CodeSniffer 3.x

### PR DESCRIPTION
**Pull request by NotTheEvilOne**
This change implements support for the new PHP_CodeSniffer namespace and classes.

### CODE REVIEW

**Comment by yunosh** [comment]
If you raise the version constraint to ^3.3, there is no need to keep the old 2.x version code. Do 3.3's PHP contraints match horde-component's PHP constraints?

**Comment by NotTheEvilOne** [comment]
The idea for the 2.x PHP CodeSniffer code was for backward compatibility with existing installations. PSR-2 has been added on @ralflang's input.

**Comment by NotTheEvilOne** [comment]
I'll remove the v2 compatibe method and PSR-2 standard then.

**Comment by yunosh** [comment]
Please leave out the tests/ folder

**Comment by NotTheEvilOne** [comment]
It's removed (hope the right one ;))

**Comment by yunosh** [comment]
Thanks!

**Pull request merged**
